apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: minio-gateway
spec:
  gatewayClassName: istio
  listeners:
  - name: storage-https
    port: 443
    protocol: HTTPS
    hostname: "*.{{ .Values.domains.storage }}"
    tls:
      certificateRefs:
      - name: minio-tls
    allowedRoutes:
      namespaces:
        from: Same
  - name: console-https
    port: 443
    protocol: HTTPS
    hostname: {{ .Values.domains.console }}
    tls:
      certificateRefs:
      - name: minio-tls
    allowedRoutes:
      namespaces:
        from: Same
