{{- range .Values.certificates }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $.Release.Name }}-certificate
spec:
  secretName: {{ .secretName }}
  dnsNames:
    {{- range .dnsNames }}
    - {{ quote . }}
    {{- end }}
  issuerRef:
    name: {{ .issuerRef.name }}
    kind: {{ .issuerRef.kind }}
{{- end }}
