{{- if .Values.configMaps }}
    {{- range .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
data:
  {{ .filename }}: |
    {{- .data | nindent 4 }}
  {{- end }}
{{- end }}
