{{- if .Values.gateway }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gateway
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:
    {{- range .Values.gateway.listeners }}
    - name: {{ .name }}
      port: 443
      protocol: HTTPS
      hostname: {{ quote .hostname }}
      tls:
        certificateRefs:
          - name: {{ .certificateName }}
      allowedRoutes:
        namespaces:
          from: Same
    {{- end }}
{{- end }}
