{{- range .Values.httpRoutes }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .name }}-route
spec:
  parentRefs:
    - name: {{ $.Release.Name }}-gateway
  {{- with .hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - backendRefs:
        - name: {{ $.Release.Name }}
          port: {{ .port }}
{{- end }}
