{{- if .Values.ingress }}
apiVersion: v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
spec:
  {{- range .Values.ingress.tls }}
  tls:
  - hosts:
    {{- range .hosts }}
    - {{ . }}
    {{- end }}
    secretName: {{ .secretName }}
  {{- end }}
  rules:
  {{- range .Values.ingress.rules }}
  - host: {{ .host }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path | default "/" }}
        pathType: {{ .pathType | default "Prefix" }}
        backend:
          service:
            name: {{ $.Chart.Name }}
            port:
              number: {{ .port }}
      {{- end }}
  {{- end }}
{{- end }}
