{{- if .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    {{- range .Values.service.ports }}
    - protocol: {{ .protocol | default "TCP" }}
      port: {{ .port }}
      targetPort: {{ .targetPort | default .port }}
    {{- end }}
  type: ClusterIP
{{- end }}
