version: 3
tasks:
  push:
    vars:
      SOURCE:
        sh: git config --get remote.origin.url
      BRANCH:
        sh: git branch --show-current
      REVISION:
        sh: git rev-parse HEAD
    cmd: flux push artifact oci://localhost:5000/homelab --path=. --source="{{.SOURCE}}" --revision="{{.BRANCH}}@sha1:{{.REVISION}}"
