Vagrant.configure("2") do |c|
    c.vm.box = "homelab/ubuntu"
    c.vm.synced_folder ".", "/vagrant", disabled: true

    c.vm.network "forwarded_port", guest: 80, host: 8080
    c.vm.network "forwarded_port", guest: 443, host: 4433
    c.vm.network "forwarded_port", guest: 6443, host: 6444

    c.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
        v.linked_clone = true
    end
end
