apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      serviceAccountName: minio-sa
      containers:
      - name: minio
        image: minio/minio:latest
        command:
        - /bin/bash
        - -c
        args:
        - minio server /data --console-address :9001
        resources:
          requests:
            cpu: "0m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 9000
        - containerPort: 9001
        env:
        - name: MINIO_DOMAIN
          value: {{ .Values.domains.storage }}
        - name: MINIO_BROWSER_REDIRECT_URL
          value: https://{{ .Values.domains.console }}
        # - name: MINIO_ROOT_USER
        #   valueFrom:
        #     secretKeyRef:
        #       key: username
        #       name: minio-secret
        # - name: MINIO_ROOT_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       key: password
        #       name: minio-secret
