apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-operator
  namespace: argocd
spec:
  project: default
  source:
    path: .
    repoURL: oci://ghcr.io/ot-container-kit/charts/redis-operator
    targetRevision: 0.24.0
  destination:
    server: https://kubernetes.default.svc
    namespace: ot-operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
