apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - namespace.yaml
  - https://github.com/traefik/traefik-helm-chart/releases/download/v34.4.1/traefik.yaml
