apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openbao-cert
spec:
  secretName: openbao-tls
  dnsNames:
  - openbao.krabi.local
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
