---
- name: Download K3s Installer
  ansible.builtin.get_url:
    url: "{{ k3s_installer }}"
    dest: /tmp/k3s-install.sh
    mode: a+x

- name: Install K3s
  ansible.builtin.command:
    cmd: /tmp/k3s-install.sh
  environment:
    INSTALL_K3S_EXEC: server --disable=traefik
  register: out
  changed_when: out.rc == 0

- name: Remove K3s Installer
  ansible.builtin.file:
    path: /tmp/k3s-install.sh
    state: absent

- name: Create kube directory
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    mode: u+rw

- name: Create a symbolic link
  ansible.builtin.file:
    src: "{{ k3s_kubeconfig }}"
    dest: /root/.kube/config
    state: link
