apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: openbao-operator
spec:
  interval: 1h
  url: oci://ghcr.io/openbao/charts/openbao
  ref:
    semver: "0.*.*"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
