workload:
  kind: Deployment # Optional, default is "Deployment"
  image: "nats:latest"
  resources: # Optional, default is empty
    limits:
      cpu: "250m"
      memory: "256Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"
service:
  ports:
    - protocol: TCP # Optional, default is "TCP"
      port: 4222
      targetPort: 4222 # Optional, default is .port
ingress:
  tls: # Optional, default is empty
    - hosts:
        - example.com
      secretName: example-tls
  rules:
    - host: example.com
      paths:
        - path: / # Optional, default is "/"
          pathType: Prefix # Optional, default is "Prefix"
          port: 4222
configMaps: # Optional, default is empty
  - name: config
    mount: /etc/config.cfg
    filename: config.cfg
    data: |
      enabled: true
