repositories:
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts

  - name: cert-manager
    url: https://charts.jetstack.io

#  - name: traefik
#    url: https://traefik.github.io/charts

#  - name: external-secrets
#    url: https://charts.external-secrets.io

#  - name: openbao
#    url: https://openbao.github.io/openbao-helm

releases:
  - name: base
    namespace: istio-system
    createNamespace: true
    chart: istio/base

  - name: istiod
    namespace: istio-system
    chart: istio/istiod
    values:
      - profile: ambient

  - name: cni
    namespace: istio-system
    chart: istio/cni
    values:
      - profile: ambient
      - global:
          platform: k3s

  - name: ztunnel
    namespace: istio-system
    chart: istio/ztunnel

  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: cert-manager/cert-manager
    values:
      - installCRDs: true
    hooks:
      - events: [ "postsync" ]
        showlogs: true
        command: kubectl
        args:
          - apply
          - -f
          - ./cert-manager/clusterissuer.yaml

#  - name: traefik
#    namespace: traefik
#    createNamespace: true
#    chart: traefik/traefik

#  - name: external-secrets
#    namespace: external-secrets
#    createNamespace: true
#    chart: external-secrets/external-secrets

#  - name: openbao
#    namespace: openbao
#    createNamespace: true
#    chart: openbao/openbao

  - name: minio
    namespace: minio
    createNamespace: true
    chart: ./minio
