---
- name: Create namespace
  kubernetes.core.k8s:
    name: "{{ argocd_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Download manifest
  ansible.builtin.get_url:
    url: "{{ argocd_manifest }}"
    dest: /tmp/argocd-manifest.yaml
    mode: a+x

- name: Apply manifest
  kubernetes.core.k8s:
    namespace: "{{ argocd_namespace }}"
    src: /tmp/argocd-manifest.yaml
    state: present

- name: Remove manifest
  ansible.builtin.file:
    path: /tmp/argocd-manifest.yaml
    state: absent

- name: Setup Ingress
  kubernetes.core.k8s:
    template: ingress.yaml.j2
    state: present
