apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-secret
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    name: minio-secret
  data:
    - secretKey: username
      remoteRef:
        key: kv/data/minio
        property: username
    - secretKey: password
      remoteRef:
        key: kv/data/minio
        property: password
