apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- certificate.yaml
- gateway.yaml
- httproute.yaml
configMapGenerator:
- name: minio-env
  literals:
  - MINIO_DOMAIN=s3.krabi.local
  - MINIO_BROWSER_REDIRECT_URL=https://minio.krabi.local
