apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: base
spec:
  interval: 12h
  chart:
    spec:
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio
