apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio
spec:
  interval: 12h
  chart:
    spec:
      chart: cni
      sourceRef:
        kind: HelmRepository
        name: istio
  values:
    profile: ambient
    global:
      platform: k3s
