apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
spec:
  interval: 12h
  chart:
    spec:
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
  dependsOn:
  - name: base
  values:
    profile: ambient
