apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - base/namespace.yaml
  - base/certificate.yaml
  - base/ingressroute.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
patches:
  - path: overlays/argocd-cmd-params-cm.yaml
